# Generated by Django 2.1.5 on 2019-02-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=200)),
                ('Nachname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=200)),
                ('Nachname', models.CharField(max_length=200)),
                ('Note', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.IntegerField(default=0)),
                ('NoteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Vorname', models.CharField(max_length=200)),
                ('Nachname', models.CharField(max_length=200)),
                ('KlasseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.IntegerField(default=0)),
                ('NoteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Unterricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Fach')),
                ('KlasseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Klasse')),
                ('Lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Lehrer')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='SchuelerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Schueler'),
        ),
        migrations.AddField(
            model_name='note',
            name='UnterrichtID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Unterricht'),
        ),
    ]
