# Generated by Django 2.1.5 on 2019-03-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kunde', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='SchuelerID',
            new_name='Schueler',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='UnterrichtID',
            new_name='Unterricht',
        ),
        migrations.RenameField(
            model_name='schueler',
            old_name='KlasseID',
            new_name='Klasse',
        ),
        migrations.RenameField(
            model_name='unterricht',
            old_name='FachID',
            new_name='Fach',
        ),
        migrations.RenameField(
            model_name='unterricht',
            old_name='KlasseID',
            new_name='Klasse',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='Name',
        ),
    ]
