# Generated by Django 2.1.5 on 2019-03-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kunde', '0002_auto_20190307_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Nachname',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Vorname',
        ),
    ]
