# Generated by Django 2.1.5 on 2019-03-28 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kunde', '0004_schunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='Nachname',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='Vorname',
        ),
        migrations.AddField(
            model_name='schueler',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
