# Generated by Django 2.1.5 on 2019-03-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kunde', '0006_auto_20190328_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einzelnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bezeichnung', models.CharField(max_length=200)),
                ('Note', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einzelnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Einzelnote')),
                ('Note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunde.Note')),
            ],
        ),
        migrations.RemoveField(
            model_name='pruefung',
            name='NoteID',
        ),
        migrations.RemoveField(
            model_name='test',
            name='NoteID',
        ),
        migrations.DeleteModel(
            name='Pruefung',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
